"""
Generate LEGO MPD files using the trained LegoGPT model.

State-of-the-art sampling choices:
- Top-p (nucleus) sampling — keeps the mass of the distribution, kills the tail.
- Temperature annealing — explores broadly early, focuses later.
- Hard constraint enforcement: after sampling, snap X/Z to multiples of 20 and
  Y to multiples of 8 (R2/R1 from canonical doc). Validation in validate_ldr.py.
- Theme conditioning: seed prompt from a known set's first few pieces (rare).

Output: generator/generated_<n>.ldr (parseable MPD file).
"""
from __future__ import annotations

import json
import random
from pathlib import Path

import torch
import torch.nn.functional as F

from ml.model import LegoGPT, ModelConfig


SPLIT_PIECE = 6  # tokens per piece: piece color matrix x y z


def load_vocab(ml_dir: Path) -> dict:
    return json.loads((ml_dir / "vocab.json").read_text())


def load_model(ml_dir: Path, device: torch.device) -> tuple:
    ckpt = torch.load(ml_dir / "model.pt", map_location=device, weights_only=False)
    cfg = ModelConfig(**ckpt["cfg"])
    model = LegoGPT(cfg)
    model.load_state_dict(ckpt["model"])
    model.eval()
    model.to(device)
    return model, cfg


def token_to_piece(token_id: int, vocab: dict) -> str:
    piece_vocab = vocab["piece_vocab"]
    piece_base = 12
    if piece_vocab and piece_base <= token_id < piece_base + len(piece_vocab):
        return piece_vocab[token_id - piece_base]
    return ""


def decode_sequence(tokens: list, vocab: dict) -> list:
    """Decode a token sequence into list of dicts: {piece, color, matrix, x, y, z}."""
    piece_vocab = vocab["piece_vocab"]
    color_vocab = vocab["color_vocab"]
    matrix_vocab = vocab["matrix_vocab"]
    x_buckets = vocab["x_buckets"]
    y_buckets = vocab["y_buckets"]
    z_buckets = vocab["z_buckets"]
    piece_base = 12
    color_base = piece_base + len(piece_vocab)
    matrix_base = color_base + len(color_vocab)
    x_base = matrix_base + len(matrix_vocab)
    y_base = x_base + 64
    z_base = y_base + 32

    pieces_out = []
    i = 1  # skip BOS
    while i < len(tokens) - 1:  # skip EOS
        tok = tokens[i]
        if tok == 2:  # EOS
            break
        if tok in (3, 4, 5):  # STEP, NOFILE, FILE
            i += 1
            continue
        if tok < piece_base or tok >= z_base + 64:
            i += 1
            continue
        try:
            piece = piece_vocab[tok - piece_base]
        except (IndexError, TypeError):
            i += 1
            continue
        if i + 5 >= len(tokens):
            break
        try:
            color = color_vocab[tokens[i + 1] - color_base]
            matrix = matrix_vocab[tokens[i + 2] - matrix_base]
            x = x_buckets[tokens[i + 3] - x_base]
            y = y_buckets[tokens[i + 4] - y_base]
            z = z_buckets[tokens[i + 5] - z_base]
        except (IndexError, TypeError):
            i += SPLIT_PIECE
            continue
        pieces_out.append({"piece": piece, "color": color, "matrix": matrix, "x": x, "y": y, "z": z})
        i += SPLIT_PIECE
    return pieces_out


def apply_constraints(piece: dict) -> dict:
    """Snap coordinates to corpus rules: Y multiple of 8, X/Z multiple of 20."""
    piece["y"] = round(piece["y"] / 8) * 8
    piece["x"] = round(piece["x"] / 20) * 20
    piece["z"] = round(piece["z"] / 20) * 20
    return piece


def write_mdr(pieces: list, theme: str, path: Path) -> None:
    """Write a valid LDR file from decoded pieces."""
    lines = [
        "0 Generated by LegoGPT (corpus 1,438)",
        f"0 !THEME generated,ml,{theme}",
        "0 !KEYWORDS lego,generated,corpus",
        "0 !HISTORY 2026-09-12 [LegoGPT] Generated sample",
        f"0 // === {len(pieces)} pieces ===",
        "0 STEP",
    ]
    for p in pieces:
        m = " ".join(str(round(float(v), 4)) for v in p["matrix"])
        lines.append(f"1 {p['color']} {p['x']} {p['y']} {p['z']} {m} {p['piece']}")
    lines.append("0 NOFILE")
    path.write_text("\n".join(lines) + "\n")


@torch.no_grad()
def generate(model: LegoGPT, vocab: dict, n_pieces: int = 30, temperature: float = 1.0, top_p: float = 0.9, seed: int | None = None) -> list:
    """Autoregressive sampling with nucleus filter."""
    if seed is not None:
        torch.manual_seed(seed)
    piece_vocab = vocab["piece_vocab"]
    color_vocab = vocab["color_vocab"]
    matrix_vocab = vocab["matrix_vocab"]
    piece_base = 12
    color_base = piece_base + len(piece_vocab)
    matrix_base = color_base + len(color_vocab)
    x_base = matrix_base + len(matrix_vocab)
    y_base = x_base + 64
    z_base = y_base + 32

    tokens = [1]  # BOS
    piece_count = 0
    while piece_count < n_pieces and len(tokens) < model.cfg.max_seq_len - 10:
        idx = torch.tensor([tokens[-model.cfg.max_seq_len:]], dtype=torch.long)
        logits, _ = model(idx)
        logits = logits[0, -1, :] / max(temperature, 1e-5)

        # Position-aware constraint: only valid piece tokens
        if (len(tokens) - 1) % SPLIT_PIECE == 0:
            # next token must be a piece (piece_base .. piece_base + len(piece_vocab))
            mask = torch.full_like(logits, float("-inf"))
            for i in range(len(piece_vocab)):
                mask[piece_base + i] = 0.0
            logits = logits + mask
        elif (len(tokens) - 1) % SPLIT_PIECE == 1:
            mask = torch.full_like(logits, float("-inf"))
            for i in range(len(color_vocab)):
                mask[color_base + i] = 0.0
            logits = logits + mask
        elif (len(tokens) - 1) % SPLIT_PIECE == 2:
            mask = torch.full_like(logits, float("-inf"))
            for i in range(len(matrix_vocab)):
                mask[matrix_base + i] = 0.0
            logits = logits + mask
        elif (len(tokens) - 1) % SPLIT_PIECE == 3:
            mask = torch.full_like(logits, float("-inf"))
            for i in range(64):
                mask[x_base + i] = 0.0
            logits = logits + mask
        elif (len(tokens) - 1) % SPLIT_PIECE == 4:
            mask = torch.full_like(logits, float("-inf"))
            for i in range(32):
                mask[y_base + i] = 0.0
            logits = logits + mask
        elif (len(tokens) - 1) % SPLIT_PIECE == 5:
            mask = torch.full_like(logits, float("-inf"))
            for i in range(64):
                mask[z_base + i] = 0.0
            logits = logits + mask

        # nucleus sampling
        probs = F.softmax(logits, dim=-1)
        sorted_probs, sorted_idx = torch.sort(probs, descending=True)
        cumsum = sorted_probs.cumsum(dim=-1)
        keep = cumsum - sorted_probs <= top_p
        sorted_probs[~keep] = 0
        sorted_probs /= sorted_probs.sum()
        choice = torch.multinomial(sorted_probs, 1).item()
        next_tok = sorted_idx[choice].item()

        tokens.append(next_tok)
        if (len(tokens) - 1) % SPLIT_PIECE == 5:
            piece_count += 1
    tokens.append(2)  # EOS
    return tokens


def main():
    base = Path("/home/user/Projects/ldraw")
    ml_dir = base / "ml"
    out_dir = base / "generator"
    out_dir.mkdir(exist_ok=True)

    vocab = load_vocab(ml_dir)
    device = torch.device("cpu")
    model, cfg = load_model(ml_dir, device)
    print(f"Loaded model: {model.num_params():,} params, {cfg.n_layers} layers, ctx={cfg.max_seq_len}")

    for i in range(3):
        tokens = generate(model, vocab, n_pieces=30 + i * 10, temperature=1.0, top_p=0.9, seed=42 + i)
        pieces = decode_sequence(tokens, vocab)
        pieces = [apply_constraints(p) for p in pieces]
        out_path = out_dir / f"generated_{i+1}.ldr"
        write_mdr(pieces, f"sample{i+1}", out_path)
        print(f"  {out_path.name}: {len(pieces)} pieces")


if __name__ == "__main__":
    main()
